### ISSUE TITLE
model from df

### ISSUE THREAD

**Issue by janikabachmann** [JonasHarnau/apc#2]
I am using the same input format as Belgian_lung_cancer.xlsx reading from excel file as data1 and data2.
Then data=[data1, data2] but from model.data_from_df(**data) get an error:
data_from_df() argument after ** must be a mapping, not list

Can you please share steps 1-6 when imported from excel?

**Comment by JonasHarnau** [comment]
When using **kwargs the input needs to be a dictionary such as `data={'response': data1, 'rate': data2}`.  Alternatively, you could use `data_from_df(response=data1, rate=data2)`.

Let me know if that helps!

**Comment by janikabachmann** [comment]
Thanks.
One problem seems to be that the xlsx file has no Age, and the initial inputs have no Age, but the Model somehow retrieves Age from somewhere, while I get a distorted df.
[APC-for-cohort-consumption/APC ConsumptionAnalysis.ipynb](url)

Error message:
ValueError                                Traceback (most recent call last)
<ipython-input-17-ec11473317cd> in <module>
      1 model=apc.Model()
----> 2 model.data_from_df(data)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apc/Model.py in data_from_df(self, response, dose, rate, data_format, time_adjust)
    145             raise ValueError("`data_format` not understood. Check the help.")
    146         if (response is not None) and not isinstance(response, pd.DataFrame):
--> 147             raise ValueError("`response` must be pandas DataFrame.")
    148         if (dose is not None) and not isinstance(dose, pd.DataFrame):
    149             raise ValueError("`dose` must be pandas DataFrame.")

ValueError: `response` must be pandas DataFrame.

**Comment by janikabachmann** [comment]
[https://github.com/janikabachmann/APC-for-cohort-consumption/blob/master/APC%20ConsumptionAnalysis.ipynb](url)

**Comment by JonasHarnau** [comment]
Thanks for providing the notebook! 

Try changing these things:
1. Add an `index_col=0` to both `read_excel` statements. So for example `pd.read_excel('hello/APC_input2.xlsx',sheet_name='cons', index_col=0)`.
2. The data have a range of years for age, but a specific year for periods (presumably that's what the column index is?). In the current form this is not supported. It's probably easiest to adjust the age indices to a single number (so for example 20, as opposed to 20-24).
2. Replace `model.data_from_df(data)` with `model.data_from_df(data_format='AP', **data)` or, alternatively, `model.data_from_df(response=data1, rate=data2, data_format='AP')`. Since your column index does not have a name the model cannot infer the `data_format` - it needs to be specified. (`AP` is assuming that this truly is an age-period array)

Let me know how it goes.

**Comment by janikabachmann** [comment]
Thanks! I got the data to the model. The model.fit for two inputs: response and rate gives an error.
On the plot charts (love these!), it groups the ages 20-25, but should show separately 20, 25,...
[APC ConsumptionAnalysis-v3.ipynb](url)
[https://github.com/janikabachmann/APC-for-cohort-consumption/blob/master/APC%20ConsumptionAnalysis-v3.ipynb](url)

**Comment by JonasHarnau** [comment]
Glad to hear you got the data into the model!

First for the plot charts from `model.plot_data_within`. By default, these plots combine the age, period and cohorts such that there are not too many groups. This is cntrolled to the `n_groups` parameter. In your case, you can set this to a higher value, for example `n_groups=10` (in which case there will still be some cohorts grouped) or even more. 

Next, whether the model uses dose and response, or rate depends on the model family. In the help (`?model.fit`), the permissable families are explained. For example, `poisson_response_rate` is not one of those. That has to do with the sensibility of the underlying model. In the Poisson case the choices are `poisson_response` or `poisson_dose_response`; in the latter case, doses are used as an offset. If you really want to use the rates as an offsets, you could just input those as the dose to begin with (`model.data_from_df(response=data1, dose=data2, data_format='AP')`).

Finally, I saw that you called `model.deviance_table` after calling `model.fit`. If you want to take a look at a deviance table, the right function to call first is `model.fit_table`, not `model.fit` - the latter is to fit a specific parameterization, the former goes through all parameterizations.

Let me know how it goes!

**Comment by janikabachmann** [comment]
Thanks a lot!
Can you please verify if OK and no misinterpretations:
[APC ConsumptionAnalysis_vF.ipynb](url)
The analysis beyond the model will be separate and very social science like.

I really like this package! Very clean and easy to use. Can see lot of use for the Poisson.

**Comment by JonasHarnau** [comment]
I just had a quick look and it looks like a good start! The deviance table indicates that you can reject a reduction to AC and PC model, but not to an AP model. 

Just two remarks from me:
- It looks like your input data is already precomputed to rates. The alternative that would lead to the same result would be to input consumption as the response and average income as the dose. Then you could fit a log-normal rate model and get the same results.
- `_vector_to_array` is useful to show you the data organized in whatever space you want, but it is not relevant for anything else in the analysis, i.e. the function does not change anything. I think you may be aware of this, but I just want to make sure.

Glad you like the package!

**Comment by janikabachmann** [comment]
Thanks a lot!
People are used to see the cohort data displayed in the _vector_to_array way, so I find this very useful.
