### ISSUE TITLE
Chart to editable format

### ISSUE THREAD

**Issue by janikabachmann** [JonasHarnau/apc#3]
Hi! Thanks for all your support. I got my paper ready for publication. Just to ask, if it is possible to output the charts not into jpg, but to some kind of editable format. I am not even sure what the editable format would be...
Thanks Janika

janikabachmann/apc

**Comment by JonasHarnau** [comment]
Hi Janika!

Glad to hear you made good progress - congratulations!

It's hard for me to say exactly what you mean by an editable format, but I can tell you that all the plots can be saved in any format matplotlib supports. Any plotting function adds the figure as an attribute to the model class. For example, if you call

```
import apc
model = apc.Model()
model.data_from_df(**apc.Belgian_lung_cancer())
model.plot_data_sums()
```

the attribute `model.plotted_data_sums` is created (any `model.plot_...` functions adds the attribute `model.plotted_...`). Then you can just use matplotlibs functionality to save the figure in any desired format. For example, you could save the figure in svg format by calling
```
model.plotted_data_sums.savefig('data_sums.svg')
```

I hope that helps!
Jonas

**Comment by janikabachmann** [comment]
Thanks!
