### ISSUE TITLE
pandas related errors in forecast and plot_parameters

### ISSUE THREAD

**Issue by m-dz** [JonasHarnau/apc#4]
Hi @JonasHarnau , first, thank you for releasing this package!

I started playing with it a little and encountered a few errors, which seem to be related to pandas version I am using. As both errors below come from pandas, could you maybe share which last version you tested the code with and check if it's working with the newest `0.25.3` version?

The simple code to replicate is as follows:

```
import apc
model = apc.Model()
model.data_from_df(apc.loss_KN(), data_format="CL", time_adjust=1)
model.fit("gen_log_normal_response", "APC")
```

and then:
```
model.forecast()
```

<details>
<summary>
causes the following `ValueError` (click to unfold)
</summary>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-87d05bd4ab9b> in <module>
----> 1 model.forecast()

~[...]/venv/lib/python3.6/site-packages/apc/Model.py in forecast(self, quantiles, method, attach_to_self)
   2404                 raise ValueError('Forecasting not supported for this family.')
   2405 
-> 2406         self._get_point_fc()
   2407 
   2408         def _agg(df, lvl):

~[...]/venv/lib/python3.6/site-packages/apc/Model.py in _get_point_fc(self, attach_to_self)
   2294         """Generate point forecasts."""
   2295         fc_design = self._get_fc_design(self.predictor)
-> 2296         fc_linpred = fc_design.dot(self.parameters['coef']).rename(
   2297             'linear_predictor_forecast')
   2298 

~[...]/venv/lib/python3.6/site-packages/pandas/core/frame.py in dot(self, other)
   1076             common = self.columns.union(other.index)
   1077             if len(common) > len(self.columns) or len(common) > len(other.index):
-> 1078                 raise ValueError("matrices are not aligned")
   1079 
   1080             left = self.reindex(columns=common, copy=False)

ValueError: matrices are not aligned
```

</details>

and
```
model.plot_parameters()
```

<details>
<summary>
causes the `KeyError: 'index'` (click to unfold)
</summary>

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~[...]/venv/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2896             try:
-> 2897                 return self._engine.get_loc(key)
   2898             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'index'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-5-e4fd0d5dc15b> in <module>
----> 1 model.plot_parameters()

~[...]/venv/lib/python3.6/site-packages/apc/Model.py in plot_parameters(self, plot_style, around_coef, simplify_ranges, figsize)
   2130         predictor = self.predictor
   2131 
-> 2132         parameters_adhoc = self.identify(plot_style, attach_to_self=False)
   2133 
   2134         def get_coefs(x):

~[...]/venv/lib/python3.6/site-packages/apc/Model.py in identify(self, style, attach_to_self)
   2018                 index=column_labels).T
   2019 
-> 2020             A_d_rows.index = A_d_rows.reset_index()['index'].apply(
   2021                 lambda x: 'A_detrend_' + x[2:])
   2022             B_d_rows.index = B_d_rows.reset_index()['index'].apply(

~[...]/venv/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2993             if self.columns.nlevels > 1:
   2994                 return self._getitem_multilevel(key)
-> 2995             indexer = self.columns.get_loc(key)
   2996             if is_integer(indexer):
   2997                 indexer = [indexer]

~[...]/venv/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897                 return self._engine.get_loc(key)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2901         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'index'
```

</details>

I am using JupyterLab within Amazon SageMaker, but this should be irrelevant here.

Python and package versions:

`Python 3.6.6 :: Anaconda, Inc.`

<details>
<summary>
Full `pip freeze` print (click to unfold)
</summary>

```
apc==1.0.1
backcall==0.1.0
clear==1.0.1
cycler==0.10.0
decorator==4.4.1
goodlogging==1.0.1
ipdb==0.12.3
ipykernel==5.1.3
ipython==7.11.1
ipython-genutils==0.2.0
jedi==0.15.2
jupyter-client==5.3.4
jupyter-core==4.6.1
kiwisolver==1.1.0
matplotlib==3.1.2
numpy==1.18.1
pandas==0.25.3
parso==0.5.2
patsy==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==3.0.2
ptyprocess==0.6.0
Pygments==2.5.2
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
pyzmq==18.1.1
quad-form-ratio==0.1.1
rarfile==2.7
requests==2.6.0
scipy==1.4.1
seaborn==0.9.0
six==1.13.0
statsmodels==0.10.2
tornado==6.0.3
traitlets==4.3.3
wcwidth==0.1.8
```

</details>

**Comment by JonasHarnau** [comment]
Hi @m-dz !

The value error from `model.forecast` is expected, but it admittedly does not come with the clearest error messages. The problem is that you are trying to forecast with an APC predictor over a forecasting array that includes parameter not encountered in the data. Specifically, the period parameter estimates for future periods don't exist. The package currently does not have the ability to extrapolate parameters. 

As for the other errors you encountered, I have to investigate more (I do also run into the errors). I believe with pandas 0.23.3 there were no problems.

**Comment by m-dz** [comment]
Thank you for replying. It is a little confusing as I did not pass any forecast data, so I assumed I would only receive forecasts for what was passed as training data. Also, the code is copied directly from https://github.com/JonasHarnau/apc/blob/master/apc/vignettes/vignette_generalized_log_normal.ipynb, which does not specify any specific forecast data as well.

I will check 0.23.3 for the plotting error.

**Comment by m-dz** [comment]
Can confirm `plot_parameters()` works with pandas 0.23.3!

**Comment by m-dz** [comment]
And to make it even more funny, I just tried running the vignette again on another PC with `python 3.6.5 :: Anaconda, Inc. and the following packages, both `.forecast()` and `.plot_parameters()` (well, actually the whole vignette) worked like a charm.

<details>
<summary>
Full `pip freeze` print (click to unfold)
</summary>

```
apc==1.0.1
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
certifi==2018.4.16
colorama==0.4.3
conda==4.5.4
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
importlib-metadata==1.4.0
ipykernel==5.1.1
ipython==7.7.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.2
Jinja2==2.10.3
json5==0.8.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterlab==1.0.2
jupyterlab-server==1.0.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.2
menuinst==1.4.14
mistune==0.8.4
more-itertools==8.1.0
nbconvert==5.6.1
nbformat==5.0.3
notebook==6.0.0
numpy==1.18.1
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.2
patsy==0.5.1
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==2.0.10
pycosat==0.6.3
Pygments==2.5.2
pyparsing==2.4.6
pyrsistent==0.15.7
python-dateutil==2.8.1
pytz==2019.3
pywinpty==0.5.7
pyzmq==18.1.1
qtconsole==4.6.0
quad-form-ratio==0.1.1
ruamel-yaml==0.15.37
scipy==1.4.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.14.0
statsmodels==0.10.2
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
win-inet-pton==1.0.1
wincertstore==0.2
zipp==1.0.0
```

</details>

**Comment by JonasHarnau** [comment]
> Thank you for replying. It is a little confusing as I did not pass any forecast data, so I assumed I would only receive forecasts for what was passed as training data. Also, the code is copied directly from https://github.com/JonasHarnau/apc/blob/master/apc/vignettes/vignette_generalized_log_normal.ipynb, which does not specify any specific forecast data as well.

The difference between your forecast code and the code in the vignette is that the vignette uses an age-cohort predictor, not an age-period-cohort predictor. Generally, the forecasts are for what is **not** in the training data. The fitted values for the training data can be accessed through `model.fitted_values`.


I just pushed some changes to the development branch. Those pass all my unit tests for pandas 0.25.2. Let me know if that fixes the issues for you!

**Comment by m-dz** [comment]
The `plot_parameters()` error seems to be gone now and I think I understand the cause of issues with `forecast()`. I wonder why `_get_fc_design()` defaults to forecasting with extrapolation (at least for the APC model) if this functionality is not supported. I'll play a bit to see whether I can get APC forecasts without the extrapolation.

**Comment by JonasHarnau** [comment]
Great!

This is actually not a configuration issue, but a "feature" of the model. With an age-period-cohort predictor, you simply cannot estimate parameters relating to future periods from the data you have. Thus, to forecast you necessarily need to extrapolate the period parameter. In an age-cohort model, you instead can forecast for future periods since you can estimate the relevant parameters from the data you already have. 

Think cohort 1950 and age 71 (period 2021). In an age-cohort model, you can estimate cohort effects for 1950 easily, and age effects for age 71 are already present for people born in 1949 and younger. However, in an age-period-cohort model, you would need the period effect for 2021 which you cannot estimate from today's data - you need to extrapolate parameters.

I hope that helps?

**Comment by m-dz** [comment]
Thank you for explanation, I will give it a bit more thought over the next few days and hopefully won't bother you any more!

I think this particular issue can be closed now when all is working if you agree.

**Comment by JonasHarnau** [comment]
Great, glad I could help!
