### ISSUE TITLE
ValueError: matrices are not aligned in model.forecast()

### ISSUE THREAD

**Issue by kevinl1210** [JonasHarnau/apc#6]
I have some wine price data as below:
![image](https://user-images.githubusercontent.com/14215103/123239100-9ec80100-d511-11eb-9054-bd62bed44b55.png)

My goal is to forecast the price in future days.

However, there is value error during forecast:
![image](https://user-images.githubusercontent.com/14215103/123239267-c6b76480-d511-11eb-87a3-f41854a89379.png)

**Comment by JonasHarnau** [comment]
Hey @kevinl1210 ,

unfortunately, this type of forecast is not supported by the package. The issue ist that you would need the future period effect to forecast for say 2022. This can be done with parameter extrapolation - but not with a simple call in the package.
